AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: ffxiv party finder notifier (EventBridge -> Lambda -> Discord webhook)

Parameters:
  DiscordWebhookUrl:
    Type: String
    NoEcho: true
    Description: Discord Webhook URL
  Limit:
    Type: Number
    Default: 5
    Description: "Max messages per run (FFXIV_PTFINDER_LIMIT)"
  DescriptionTerms:
    Type: String
    Default: "最初から"
    Description: "Comma-separated or JSON array for description filter terms (FFXIV_PTFINDER_DESCRIPTION_TERMS)"
  DescriptionMode:
    Type: String
    Default: "and"
    AllowedValues:
      - and
      - or
    Description: "Description filter mode: and/or (FFXIV_PTFINDER_DESCRIPTION_MODE)"
  FilterJson:
    Type: String
    Default: ""
    Description: "Optional JSON filter object (FFXIV_PTFINDER_FILTER_JSON)"
  FilterFile:
    Type: String
    Default: "data/filter.json"
    Description: "Path to JSON filter file in the deployment package (FFXIV_PTFINDER_FILTER_FILE)"

Resources:
  PtfinderFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: ffxiv-ptfinder-notifier
      Runtime: nodejs20.x
      Architectures:
        - arm64
      Handler: dist/lambdaHandler.handler
      CodeUri: .
      MemorySize: 512
      Timeout: 120
      Environment:
        Variables:
          DISCORD_WEBHOOK_URL: !Ref DiscordWebhookUrl
          FFXIV_PTFINDER_LIMIT: !Ref Limit
          FFXIV_PTFINDER_DESCRIPTION_TERMS: !Ref DescriptionTerms
          FFXIV_PTFINDER_DESCRIPTION_MODE: !Ref DescriptionMode
          FFXIV_PTFINDER_FILTER_JSON: !Ref FilterJson
          FFXIV_PTFINDER_FILTER_FILE: !Ref FilterFile
      Events:
        Schedule30m:
          Type: Schedule
          Properties:
            Schedule: rate(30 minutes)
            Enabled: true
    Metadata:
      BuildMethod: makefile

Outputs:
  FunctionName:
    Value: !Ref PtfinderFunction
  FunctionArn:
    Value: !GetAtt PtfinderFunction.Arn
